trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: 'DevOps-Path/Continuous Integration and Continuous Deployment (CICD) with Azure DevOps/vnet/'
    backendServiceArm: 'Mike-Pay-As-You-Go(220284d2-6a19-4781-87f8-5c564ec4fec9)'
    backendAzureRmResourceGroupName: 'CBTAzure'
    backendAzureRmStorageAccountName: 'storageaccountcbtaza341'
    backendAzureRmContainerName: 'azure-webjobs-hosts'
    backendAzureRmKey: 'tf/terraform.tfstate'

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: 'DevOps-Path/Continuous Integration and Continuous Deployment (CICD) with Azure DevOps/vnet/'
    commandOptions: '-var="subscriptionID=$(subscriptionID" -var="location=$(location) -var="resourceGroupName=$(resourceGroupName)"'
    environmentServiceNameAzureRM: 'Mike-Pay-As-You-Go(220284d2-6a19-4781-87f8-5c564ec4fec9)'
