# Python MySQL must be installed on the remote hosts. To install:
# apt-get install python-pymysql

---
- hosts: sqlserver01
  become: true
  vars:
    mysql_user: cbt
    mysql_password: root

  tasks:
  - name: Install pymysql
    shell: apt install python-pymysql

  - name: Install MySQL
    shell: apt install mysql-server

  - name: MySQL 
    mysql_db:
      name: cbtdata
      state: present
  
  - name: Configure MySQL users
    mysql_users:
    - name: "${{ mysql_user }}"
      host: "%"
      password: "${{ mysql_password }}"
      priv: "example_db.*:ALL"