# Python MySQL must be installed on the remote hosts. To install:
# apt-get install python-pymysql

---
- hosts: sqlserver01
  become: true
  vars:
    mysql_user_name: cbt
    mysql_user_password: root
    mysql_root_password_update: false

  tasks:
  - name: Install pymysql
    shell: apt install python-pymysql

  - name: Install MySQL
    shell: apt install mysql-server

  - name: MySQL 
    mysql_db:
      name: cbtdata
      state: present