# Python MySQL must be installed on the remote hosts. To install:
# apt-get install python-pymysql

---
- hosts: sqlserver01
  become: true
  vars:
    mysql_user: cbt
    mysql_password: root

  tasks:
  - name: Install pymysql
    shell: apt install python-pymysql -y

  - name: Install MySQL
    shell: apt install mysql-server -y

  - name: Configure MySQL users
    mysql_user:
      name: "${{ mysql_user }}"
      host: "%"
      priv: '*.*:ALL'
      state: present

  - name: MySQL 
    mysql_db:
      login_user: "${{ mysql_user }}"
      login_password: "${{ mysql_password }}"
      name: cbtdata
      state: present
