name: AKS-and-ACI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        name: ['cbtaks']
        resourceGroupName: ['CBTAzure']
        location: ['eastus']
        kubernetesVersion: ['1.16.7']
        nodeCount: [1]

    steps:
    - uses: actions/checkout@v2

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Run a one-line script
      run: pwsh -command .\PowerShell-For-DevOps-Automation\AKS-And-ACI\New-AKSCluster.ps1  -name ${{ matrix.name }} -resourceGroupName ${{ matrix.resourceGroupName }} -location ${{ matrix.location }} -kubernetesVersion ${{ matrix.kubernetesVersion }} -nodeCount ${{ matrix.nodeCount }}